# Generated by Django 4.2.2 on 2023-07-19 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.DecimalField(decimal_places=1, max_digits=3)),
                ('comentario', models.TextField()),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('sinopse', models.TextField()),
                ('genero', models.CharField(max_length=50)),
                ('duracao', models.CharField(max_length=50)),
                ('ano_lancamento', models.PositiveIntegerField()),
                ('diretor', models.CharField(max_length=100)),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='filmes/')),
                ('imagem_bg', models.ImageField(blank=True, null=True, upload_to='filmes/')),
                ('url_slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('sinopse', models.TextField()),
                ('genero', models.CharField(max_length=50)),
                ('qtd_temporadas', models.CharField(max_length=50)),
                ('ano_estreia', models.PositiveIntegerField()),
                ('criador', models.CharField(max_length=100)),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='series/')),
                ('imagem_bg', models.ImageField(blank=True, null=True, upload_to='series/')),
                ('url_slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_comentario', models.DateTimeField(auto_now_add=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='graphflix_app.avaliacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='filme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graphflix_app.filme'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='serie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graphflix_app.serie'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
