# Generated by Django 5.1.3 on 2024-11-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphflix_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulo',
            name='tipo',
            field=models.CharField(choices=[('filme', 'Filme'), ('serie', 'Série')], default='filme', max_length=5),
        ),
    ]
