# Generated by Django 5.1.2 on 2024-11-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphflix_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
