# Generated by Django 5.1.2 on 2024-11-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphflix_app', '0002_alter_genero_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulo',
            name='avaliacao',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='backdropPath',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='classificacao',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='posterPath',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='sinopse',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
