# Generated by Django 5.1.2 on 2024-11-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphflix_app', '0004_alter_filme_diretor_alter_serie_criador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulo',
            name='backdropPath',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='posterPath',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
