# Generated by Django 5.1.2 on 2024-11-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphflix_app', '0005_alter_titulo_backdroppath_alter_titulo_posterpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulo',
            name='backdropPath',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='posterPath',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
